version: '3.8'

services:
  relay:
    image: laithaj/gorelayserve:latest
    container_name: go_relay
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    # For Linux users with local Redis, uncomment:
    # network_mode: host
